import Foundation
import Testing
@testable import BridgeCore

@Test func parsesADIFAndMapsWavelogCreate() throws {
    let adif = """
    Generated by a logger
    <ADIF_VER:5>3.1.7
    <EOH>
    <CALL:6>VK8ABC<BAND:3>20M<MODE:2>FT<QSO_DATE:8>20261004<TIME_ON:6>102030<FREQ:9>14.074000<RST_SENT:3>-10<RST_RCVD:3>-08<GRIDSQUARE:6>PH57aa<EOR>
    """
    let records = ADIFParser().records(in: adif)
    let record = try #require(records.first)
    #expect(records.count == 1)
    #expect(record["CALL"] == "VK8ABC")

    let create = try #require(WavelogQSOCreate(adif: record))
    #expect(create.qsoDate == "2026-10-04")
    #expect(create.timeOn == "102030")
    #expect(create.frequency == 14_074_000)
    #expect(create.gridSquare == "PH57aa")
    #expect(record.adifDocument.contains("<CALL:6>VK8ABC"))
    #expect(record.adifDocument.hasSuffix("<EOR>\r\n"))
}

@Test func filtersKnownADIFRecordWithoutReencodingRemainingRecord() throws {
    let first = "<CALL:3>AAA<BAND:3>20M<MODE:2>CW<QSO_DATE:8>20260101<TIME_ON:6>010203<FREQ:6>14.050<EOR>"
    let second = "<CALL:3>BBB<BAND:3>40M<MODE:3>SSB<QSO_DATE:8>20260102<TIME_ON:6>040506<FREQ:5>7.100<EOR>"
    let adif = "header<EOH>\r\n\(first)\r\n\(second)\r\n"
    let parser = ADIFParser()
    let known = try #require(parser.records(in: first).first?.semanticIdentityHash)
    let filtered = parser.removingKnownRecords(from: adif, knownFingerprints: [known])
    #expect(filtered.records.count == 1)
    #expect(filtered.records.first?["CALL"] == "BBB")
    #expect(!filtered.adif.contains(first))
    #expect(filtered.adif.contains(second))
}

@Test func semanticIdentityIgnoresFrequencyFormattingZeros() {
    let compact = SemanticQSOIdentity(
        call: "9H1CJ",
        timestamp: "20221008150236",
        band: "15m",
        mode: "SSB",
        frequency: "21.3178"
    )
    let padded = SemanticQSOIdentity(
        call: "9h1cj",
        timestamp: "20221008150236",
        band: "15M",
        mode: "ssb",
        frequency: "21.317800"
    )
    #expect(compact == padded)
    #expect(compact.sha256 == padded.sha256)
}

@Test func semanticIdentitySurvivesRumlogADIFCanonicalization() throws {
    let remote = ADIFRecord(fields: [
        "CALL": "UE6DR",
        "QSO_DATE": "20260612",
        "TIME_ON": "063700",
        "QSO_DATE_OFF": "20260612",
        "TIME_OFF": "063800",
        "BAND": "17m",
        "MODE": "FT8",
        "FREQ": "18.10145",
    ])
    let rumlog = ADIFRecord(fields: [
        "CALL": "UE6DR",
        "QSO_DATE": "20260612",
        "TIME_ON": "063800",
        "QSO_DATE_OFF": "20260612",
        "TIME_OFF": "063800",
        "BAND": "17m",
        "MODE": "FT8",
        "FREQ": "18.101500",
    ])

    #expect(remote.semanticIdentityHash == rumlog.semanticIdentityHash)
}

@Test func bridgeFileStorePersistsSettingsAndBootstrapSeparately() async throws {
    let directory = FileManager.default.temporaryDirectory
        .appendingPathComponent("bridge-store-\(UUID().uuidString)", isDirectory: true)
    defer { try? FileManager.default.removeItem(at: directory) }
    let store = try BridgeFileStore(directoryURL: directory)
    var settings = BridgeSettings()
    settings.stationID = 2
    settings.stationName = "Darwin NT"
    try await store.saveSettings(settings)
    try await store.saveBootstrapState(BootstrapState(
        stationID: 2,
        nextPage: 4,
        importedCount: 1_500,
        totalCount: 2_000,
        lastFetchedID: 99
    ))

    #expect(try await store.loadSettings() == settings)
    let progress = try await store.loadBootstrapState(stationID: 2)
    #expect(progress.nextPage == 4)
    #expect(progress.importedCount == 1_500)
    #expect(try await store.loadBootstrapState(stationID: 1).importedCount == 0)
    let continuous = ContinuousSyncState(
        stationID: 2,
        lastWavelogID: 99,
        knownFingerprints: ["abc"]
    )
    try await store.saveContinuousSyncState(continuous)
    #expect(try await store.loadContinuousSyncState(stationID: 2) == continuous)
    #expect(try await store.loadContinuousSyncState(stationID: 1).knownFingerprints.isEmpty)
}

@Test(.enabled(if: ProcessInfo.processInfo.environment["RUN_RUMLOG_INTEGRATION"] == "1"))
func readsFromRunningRumlogViaSupportedAppleEvent() async throws {
    let client = RumlogAppleEventClient()
    #expect(client.isInstalled())
    #expect(client.isRunning())
    let adif = try await Task.detached {
        try client.exportADIF(since: "1970-01-01 00:00:00")
    }.value
    print("RUMLOG_READ_RECORDS=\(ADIFParser().records(in: adif).count)")
    #expect(adif.isEmpty || adif.uppercased().contains("ADIF") || adif.uppercased().contains("EOH"))
}

@Test(.enabled(if: ProcessInfo.processInfo.environment["RUN_LIVE_BOOTSTRAP"] == "1"))
func importsOneLiveWavelogContactIntoOpenRumlog() async throws {
    let environment = ProcessInfo.processInfo.environment
    let token = try #require(environment["WAVELOG_TOKEN"])
    let baseURL = try #require(URL(string: environment["WAVELOG_URL"] ?? ""))
    let stationID = try #require(Int(environment["WAVELOG_STATION_ID"] ?? ""))
    let wavelog = WavelogClient(configuration: try WavelogConfiguration(
        baseURL: baseURL,
        token: token,
        stationID: stationID
    ))
    let page = try await wavelog.exportADIF(page: 1, perPage: 1)
    #expect(page.data.exported == 1)

    let rumlog = RumlogAppleEventClient()
    try await Task.detached { try rumlog.importADIF(page.data.adif) }.value
    let exported = try await Task.detached {
        try rumlog.exportADIF(since: "1970-01-01 00:00:00")
    }.value
    let records = ADIFParser().records(in: exported)
    let calls = records.prefix(3).compactMap { $0["CALL"] }.joined(separator: ",")
    print("RUMLOG_EXPORT_RECORDS=\(records.count) CALLS=\(calls)")
    #expect(records.count >= 1)
}
